"""Administration view for Feishu users, scoped to a managed application."""

FEISHU_USERS_PAGE = r'''<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<script src="https://cdn.tailwindcss.com"></script><title>飞书用户管理</title></head>
<body class="min-h-screen bg-slate-950 p-7 text-slate-100">
  <a href="/admin" class="text-sm text-sky-300">← 返回管理平台</a>
  <div class="mt-5 flex items-end justify-between"><div><h1 class="text-2xl font-bold">飞书用户管理</h1><p class="mt-2 text-sm text-slate-400">请选择飞书应用。用户、权限、局部提示词和会话均按应用隔离。</p></div><button onclick="load()" class="rounded bg-sky-500 px-3 py-2 text-sm">刷新</button></div>
  <div class="mt-5 flex items-center gap-3 rounded-xl border border-slate-800 bg-slate-900/60 p-4"><label for="application-filter" class="text-sm font-semibold">飞书应用</label><select id="application-filter" class="min-w-72 rounded-lg border border-slate-700 bg-slate-950 px-3 py-2 text-sm"></select><span id="hint" class="text-xs text-slate-400"></span></div>
  <div class="mt-6 overflow-x-auto rounded-xl border border-slate-800"><table class="w-full text-left text-sm"><thead class="bg-slate-900 text-slate-400"><tr><th class="p-4">飞书用户</th><th>角色</th><th>额外工具</th><th>最终工具</th><th>会话</th><th>状态</th><th>操作</th></tr></thead><tbody id="rows"></tbody></table></div>
  <dialog id="edit" class="w-full max-w-2xl rounded-xl border border-slate-700 bg-slate-900 p-6 text-slate-100"><form method="dialog"><div class="flex justify-between"><h2 id="name" class="text-lg font-bold"></h2><button>×</button></div><p class="mt-1 text-xs text-slate-400" id="openid"></p><h3 class="mt-5 font-semibold">额外绑定角色</h3><div id="roles" class="mt-2 grid gap-2 sm:grid-cols-2"></div><h3 class="mt-5 font-semibold">额外工具</h3><div id="tools" class="mt-2 grid gap-2 sm:grid-cols-2"></div><label class="mt-5 flex gap-2"><input id="active" type="checkbox"> 启用该飞书用户</label><div class="mt-6 flex justify-end gap-3"><button>取消</button><button type="button" onclick="save()" class="rounded bg-emerald-400 px-4 py-2 font-semibold text-slate-950">保存</button></div></form></dialog>
<script>
let users=[], roles=[], tools=[], applications=[], selected=null, selectedApplicationId='';
const e=s=>document.querySelector(s); const esc=s=>String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
async function api(path, options={}) { const response=await fetch('/admin'+path,{headers:{'Content-Type':'application/json'},...options}); if(!response.ok) throw Error((await response.json()).detail||'请求失败'); return response.status===204?null:response.json(); }
function chips(items, field='name') { return items.length ? items.map(item=>`<span class="mr-1 inline-block rounded bg-slate-800 px-2 py-1 text-xs" title="${esc(item[field])}">${esc(item[field])}</span>`).join('') : '—'; }
function render() { e('#rows').innerHTML=users.map(user=>`<tr class="border-t border-slate-800"><td class="p-4"><div class="font-semibold">${esc(user.display_name)}</div><div class="mt-1 font-mono text-xs text-slate-500">${esc(user.open_id)}</div></td><td>${chips(user.role_ids.map(id=>roles.find(item=>item.id===id)).filter(Boolean))}</td><td>${chips(user.extra_tool_ids.map(id=>tools.find(item=>item.id===id)).filter(Boolean))}</td><td>${chips(user.effective_tools)}</td><td><button onclick="sessions('${user.id}')" class="text-sky-300">${user.session_count} 个会话</button></td><td><span class="rounded px-2 py-1 text-xs ${user.is_active?'bg-emerald-500/20 text-emerald-300':'bg-slate-700'}">${user.is_active?'启用':'禁用'}</span></td><td><button onclick="openEdit('${user.id}')" class="text-sky-300">编辑</button></td></tr>`).join('')||'<tr><td colspan="7" class="p-10 text-center text-slate-500">该飞书应用尚未收到用户消息</td></tr>'; }
function renderApplications() { const filter=e('#application-filter'); filter.innerHTML=applications.map(app=>`<option value="${app.id}">${esc(app.name)} · ${esc(app.api_key_name)}</option>`).join(''); filter.value=selectedApplicationId; e('#hint').textContent=applications.length?'仅显示当前应用的用户、会话和权限。':'请先在飞书应用管理中创建应用。'; }
async function load() { [applications,roles,tools]=await Promise.all([api('/feishu-applications'),api('/roles'),api('/mcp-tools')]); if(!applications.some(app=>app.id===selectedApplicationId)) selectedApplicationId=applications[0]?.id||''; renderApplications(); users=selectedApplicationId?await api('/feishu-users?application_id='+encodeURIComponent(selectedApplicationId)):[]; render(); }
function openEdit(id) { selected=users.find(user=>user.id===id); e('#name').textContent=selected.display_name; e('#openid').textContent=selected.open_id; e('#active').checked=selected.is_active; e('#roles').innerHTML=roles.map(item=>`<label><input type="checkbox" value="${item.id}" ${selected.role_ids.includes(item.id)?'checked':''}> ${esc(item.name)}</label>`).join(''); e('#tools').innerHTML=tools.map(item=>`<label><input type="checkbox" value="${item.id}" ${selected.extra_tool_ids.includes(item.id)?'checked':''}> ${esc(item.name)}</label>`).join(''); e('#edit').showModal(); }
async function save() { const checked=selector=>[...document.querySelectorAll(selector+':checked')].map(node=>node.value); await api('/feishu-users/'+selected.id,{method:'PUT',body:JSON.stringify({role_ids:checked('#roles input'),extra_tool_ids:checked('#tools input'),is_active:e('#active').checked})}); e('#edit').close(); await load(); }
async function sessions(id) { const records=await api('/feishu-users/'+id+'/sessions'); alert(records.map(item=>`${item.is_archived?'[已隐藏] ':''}${item.title}\n${item.last_used_at}`).join('\n\n')||'暂无会话'); }
e('#application-filter').addEventListener('change',async event=>{ selectedApplicationId=event.target.value; await load(); });
load().catch(error=>alert(error.message));
</script></body></html>'''
